#!/bin/sh

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage() {
    printf 'Usage: %s [-b IMAGE] CNAME\n' "${0##*/}"
}

base='debian:unstable'
while getopts 'b:h' opt
do
    case $opt in
        h)
            usage
            exit 0;;
        b)
            base="$OPTARG";;
        *)
            exit 1;;
    esac
done
shift $((OPTIND - 1))
if [ $# -ne 1 ]
then
    usage >&2
    exit 1
fi
cname="$1"
exec docker run -d -v "$HOME:$HOME" --init --name "$cname" -- "$base" sleep inf

# vim:ts=4 sts=4 sw=4 et
