#!/bin/sh

# Copyright © 2022-2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage() {
    printf 'Usage: %s CNAME [COMMAND...]\n' "${0##*/}"
}
if [ $# -lt 1 ]
then
    usage >&2
    exit 1
fi
cname="$1"
shift
if [ $# -eq 0 ]
then
    set -- su
fi
exec docker exec -it -- "$cname" "$@"

# vim:ts=4 sts=4 sw=4 et
