#!/bin/sh

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

docker images --format '{{.Repository}}:{{.Tag}}' \
| grep -v ':<none>$' \
| sort -u \
| xargs -t -L1 docker pull

# vim:ts=4 sts=4 sw=4 et
