#!/bin/sh

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage() {
    printf 'Usage: %s CNAME\n' "${0##*/}"
}
if [ $# -ne 1 ]
then
    usage >&2
    exit 1
fi
cname="$1"
uid=$(id -u)
exec docker exec -- "$cname" adduser --uid "$uid" "$LOGNAME" < /dev/null

# vim:ts=4 sts=4 sw=4 et
