#!/bin/sh

# Copyright © 2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage() {
    printf 'Usage: %s REPO\n' "${0##*/}"
}
if [ $# -ne 1 ]
then
    usage >&2
    exit 1
fi
repo="$1"

case repo in
    *://*) ;;
    *) repo="docker://docker.io/$repo";;
esac
json=$(skopeo list-tags "$repo")
jq -r '.Tags[]' <<EOF
$json
EOF

# vim:ts=4 sts=4 sw=4 et
