#!/bin/sh

# Copyright © 2022-2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage() {
    printf 'Usage: %s CNAME\n' "${0##*/}"
}
if [ $# -ne 1 ]
then
    usage >&2
    exit 1
fi
cname="$1"
json=$(docker manifest inspect "$cname")
jq -r '.manifests[] | .platform.os + "/" + .platform.architecture' <<EOF
$json
EOF

# vim:ts=4 sts=4 sw=4 et
